### PR TITLE
Release Pulsar Flex 1.0.10

### PR DESCRIPTION
**Pull request by pruzze**
This change is [Reviewable](https://reviewable.io/reviews/dse-ab/artifacts/37)

### CODE REVIEW

**Comment by DSE-FredrikEngberg** [comment]
*[pulsar/spa-ui-1.0.10.properties, line 6 at r1](https://reviewable.io:443/reviews/dse-ab/artifacts/37#-KnitgCfWywCIqPEMKlw:-KnitgCfWywCIqPEMKlx:b-fmu1t4) ([raw file](https://github.com/dse-ab/artifacts/blob/ef9e1e45121159b7d2a5ec3aa00f1f2cbc856068/pulsar/spa-ui-1.0.10.properties#L6)):*
> ```INI
> apps=core/4.1.0/pulsar-apps-4.1.0.pulsar
> endorsed=core/4.1.0/pulsar-endorsed-4.1.0.pulsar
> docs=core/4.1.0/Pulsar Core - Release 4.1.0.pdf
> ```

Borde vi inte döpa PDF:en enligt tidigare konvention, "Pulsar 4.1.0 Documentation"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/37)*

**Comment by DSE-FredrikEngberg** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/37)*

**Comment by pruzze** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pulsar/spa-ui-1.0.10.properties, line 6 at r1](https://reviewable.io:443/reviews/dse-ab/artifacts/37#-KnitgCfWywCIqPEMKlw:-Kniua6j6HB_vC_87IQP:bfa55b4) ([raw file](https://github.com/dse-ab/artifacts/blob/ef9e1e45121159b7d2a5ec3aa00f1f2cbc856068/pulsar/spa-ui-1.0.10.properties#L6)):*
<details><summary><i>Previously, DSE-FredrikEngberg (Fredrik Engberg) wrote…</i></summary><blockquote>

Borde vi inte döpa PDF:en enligt tidigare konvention, "Pulsar 4.1.0 Documentation"?
</blockquote></details>

Aha, jag trodde att du hade ändrat med flit. För du hade ändrat rubrik i Confluence? Men jag fixar det!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/37)*

**Comment by pruzze** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pulsar/spa-ui-1.0.10.properties, line 6 at r1](https://reviewable.io:443/reviews/dse-ab/artifacts/37#-KnitgCfWywCIqPEMKlw:-KnivJXbyH4zFpMeTnrw:b-886gvx) ([raw file](https://github.com/dse-ab/artifacts/blob/ef9e1e45121159b7d2a5ec3aa00f1f2cbc856068/pulsar/spa-ui-1.0.10.properties#L6)):*
<details><summary><i>Previously, pruzze (Fredrik Prüzelius) wrote…</i></summary><blockquote>

Aha, jag trodde att du hade ändrat med flit. För du hade ändrat rubrik i Confluence? Men jag fixar det!
</blockquote></details>

Fixat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/37)*

**Comment by DSE-FredrikEngberg** [comment]
*[pulsar/spa-ui-1.0.10.properties, line 6 at r1](https://reviewable.io:443/reviews/dse-ab/artifacts/37#-KnitgCfWywCIqPEMKlw:-KnivaI1U7HJNuIMsM4j:b5453iz) ([raw file](https://github.com/dse-ab/artifacts/blob/ef9e1e45121159b7d2a5ec3aa00f1f2cbc856068/pulsar/spa-ui-1.0.10.properties#L6)):*
<details><summary><i>Previously, pruzze (Fredrik Prüzelius) wrote…</i></summary><blockquote>

Fixat
</blockquote></details>

Jo, det var för att få rätt titel på dokumentet :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/37)*

**Comment by DSE-FredrikEngberg** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/37)*

**Comment by DSE-FredrikEngberg** [comment]
*[pulsar/spa-ui-1.0.10.properties, line 6 at r1](https://reviewable.io:443/reviews/dse-ab/artifacts/37#-KnitgCfWywCIqPEMKlw:-Knivk4fLe0ikX6sUNO5:b3zzf07) ([raw file](https://github.com/dse-ab/artifacts/blob/ef9e1e45121159b7d2a5ec3aa00f1f2cbc856068/pulsar/spa-ui-1.0.10.properties#L6)):*
<details><summary><i>Previously, DSE-FredrikEngberg (Fredrik Engberg) wrote…</i></summary><blockquote>

Jo, det var för att få rätt titel på dokumentet :-)
</blockquote></details>

På förstasidan

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/37)*

**Comment by pruzze** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pulsar/spa-ui-1.0.10.properties, line 6 at r1](https://reviewable.io:443/reviews/dse-ab/artifacts/37#-KnitgCfWywCIqPEMKlw:-KniyV41F-zgbudpI-Ux:b-2sra3l) ([raw file](https://github.com/dse-ab/artifacts/blob/ef9e1e45121159b7d2a5ec3aa00f1f2cbc856068/pulsar/spa-ui-1.0.10.properties#L6)):*
<details><summary><i>Previously, DSE-FredrikEngberg (Fredrik Engberg) wrote…</i></summary><blockquote>

På förstasidan
</blockquote></details>

Fixat som sagt! :-) Sista pull requesten!?!?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/37)*

**Pull request merged**
