### PR TITLE
Release Pulsar Snapshot 170531-1424

### PR DESCRIPTION
**Pull request by DSE-FredrikEngberg**
This change is [Reviewable](https://reviewable.io/reviews/dse-ab/artifacts/31)

### CODE REVIEW

**Comment by pruzze** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[pulsar/pulsar-snapshot-170302-2331.properties, line 5 at r1](https://reviewable.io:443/reviews/dse-ab/artifacts/31#-KlTgHtrVxdWvNaMtnd0:-KlTgHtrVxdWvNaMtnd1:b-ezuza5) ([raw file](https://github.com/dse-ab/artifacts/blob/05bee0cf7d20ac6bc2d6ec358707c791863e3cd2/pulsar/pulsar-snapshot-170302-2331.properties#L5)):*
> ```INI
> apps=core/snapshot/4.1.0.1.170302-2331/pulsar-apps-4.1.0.1.170302-2331-develop.pulsar
> endorsed=core/snapshot/4.1.0.1.170302-2331/pulsar-endorsed-4.1.0.170302-2353-feature-PULSAR-672.pulsar
> docs=core/4.0.2/Pulsar 4.0.2 Documentation.pdf
> ```

Vad är detta för fil? Ska den med?

---

*[pulsar/spa-ui/1.0.7/spa-ui-1.0.7.pulsar, line 0 at r1](https://reviewable.io:443/reviews/dse-ab/artifacts/31#-KlTgsTt4Dayq2iubw1T:-KlTgsTt4Dayq2iubw1U:b-onlf23) ([raw file](https://github.com/dse-ab/artifacts/blob/05bee0cf7d20ac6bc2d6ec358707c791863e3cd2/pulsar/spa-ui/1.0.7/spa-ui-1.0.7.pulsar#L0)):*
Kom du på varför denna filen kom med?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/31)*

**Comment by DSE-FredrikEngberg** [comment]
*[pulsar/spa-ui/1.0.7/spa-ui-1.0.7.pulsar, line  at r1](https://reviewable.io:443/reviews/dse-ab/artifacts/31#-KlTgsTt4Dayq2iubw1T:-Klc5LRelmuXMJJq8fNZ:b1s003l) ([raw file](https://github.com/dse-ab/artifacts/blob/05bee0cf7d20ac6bc2d6ec358707c791863e3cd2/pulsar/spa-ui/1.0.7/spa-ui-1.0.7.pulsar#L)):*
<details><summary><i>Previously, pruzze (Fredrik Prüzelius) wrote…</i></summary><blockquote>

Kom du på varför denna filen kom med?
</blockquote></details>

Nej, tror att det är något knas med LFS. Det går inte att se någon diff lokalt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/31)*

**Comment by DSE-FredrikEngberg** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[pulsar/pulsar-snapshot-170302-2331.properties, line 5 at r1](https://reviewable.io:443/reviews/dse-ab/artifacts/31#-KlTgHtrVxdWvNaMtnd0:-Klc56a45aCFq8G5Lxij:b-jp5970) ([raw file](https://github.com/dse-ab/artifacts/blob/05bee0cf7d20ac6bc2d6ec358707c791863e3cd2/pulsar/pulsar-snapshot-170302-2331.properties#L5)):*
<details><summary><i>Previously, pruzze (Fredrik Prüzelius) wrote…</i></summary><blockquote>

Vad är detta för fil? Ska den med?
</blockquote></details>

Det är den som hette `pulsar-develop` tidigare.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/31)*

**Comment by pruzze** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dse-ab/artifacts/31)*

**Pull request merged**
